minimum_prek_version = "0.4.5"
default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "commitlint"
name = "commitlint"
entry = "npx --no-install commitlint --edit"
language = "system"
stages = ["commit-msg"]
always_run = true
