name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: avrea-ubuntu-latest-2-vcpu
    name: Test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.16.0
      - run: zig fmt --check build.zig build.zig.zon benchmarks experiments src
      - run: zig build test
      - run: zig build test-acceptance

  metal-test:
    runs-on: avrea-macos-latest-8-vcpu
    name: Metal Test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        with:
          version: 0.16.0
      - run: zig build -Dgpu=metal test-metal_backend --summary all
      - run: zig build -Dgpu=metal run_gpu
